AllCops:
  NewCops: enable
  Exclude:
    - 'spec/*.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  
Layout/EndOfLine:
  EnforcedStyle: lf