AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  
Metrics/BlockLength:
  Exclude:
    - 'labs/lab1/spec/*.rb'
    - 'labs/lab2/spec/*.rb'
  
Layout/EndOfLine:
  EnforcedStyle: lf